import { Montserrat } from "next/font/google";
import "./globals.scss";
import ProviderWrap from "@/components/providerWrap/ProviderWrap";
import Header from "@/components/header/Header";
import { Footer } from "@/components/footer/Footer";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<ProviderWrap>
					<Header />
					<main>{children}</main>
					<Footer />
				</ProviderWrap>
			</body>
		</html>
	);
}
